/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.BorderFactory;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;

/**
 *
 * @author Asus
 */
public class TieBreaker extends javax.swing.JFrame implements ChangeListener {

    /**
     * Creates new form TieBreaker
     */
    String player1Name;
    String player2Name;
    int player1Score;
    int player2Score;
    int chance = 0;    
    int newScore=0;

//    public TieBreaker(String player1Name, String player2Name, int player1Score, int player2Score) {
//        initComponents();
//        this.player1Name = player1Name;
//        this.player2Name = player2Name;
//        this.player1Score = player1Score;
//        this.player2Score = player2Score;
//        p1Panel.setBorder(BorderFactory.createTitledBorder(player1Name));
//        p2Panel.setBorder(BorderFactory.createTitledBorder(player2Name));
//        p2OriginalScore.setText(String.valueOf(player2Score));
//        p1OriginalScore.setText(String.valueOf(player1Score));
//        p1f1.setText(String.valueOf(player1Score));
//        display.setText(player2Name +" is the 2nd highest player\n therefore he will get a chance to bowl");      
//    }

    public TieBreaker() {
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        p1Panel = new javax.swing.JLayeredPane();
        p1OriginalScore = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        p1c1 = new javax.swing.JTextField();
        p1f1 = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        p1c21 = new javax.swing.JTextField();
        p1c22 = new javax.swing.JTextField();
        p1c23 = new javax.swing.JTextField();
        p1f2 = new javax.swing.JTextField();
        p2Panel = new javax.swing.JLayeredPane();
        p2OriginalScore = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        p2c1 = new javax.swing.JTextField();
        p2f1 = new javax.swing.JTextField();
        jPanel13 = new javax.swing.JPanel();
        jPanel14 = new javax.swing.JPanel();
        jPanel15 = new javax.swing.JPanel();
        p2c21 = new javax.swing.JTextField();
        p2c22 = new javax.swing.JTextField();
        p2c23 = new javax.swing.JTextField();
        p2f2 = new javax.swing.JTextField();
        angleSlider = new javax.swing.JSlider();
        velocitySlider = new javax.swing.JSlider();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        angleValue = new javax.swing.JLabel();
        velocityValue = new javax.swing.JLabel();
        throwBallButton = new javax.swing.JButton();
        exit = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        display = new javax.swing.JTextArea();

        jLabel1.setText("jLabel1");

        jTextField2.setEditable(false);
        jTextField2.setText("jTextField2");

        jLabel4.setText("jLabel4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(800, 800));

        jPanel1.setLayout(new java.awt.GridLayout(1, 0));

        jPanel2.setLayout(new java.awt.GridLayout(1, 0));

        jPanel3.setLayout(new java.awt.GridLayout(1, 0));

        p1Panel.setBorder(javax.swing.BorderFactory.createTitledBorder("Player1 Name"));
        p1Panel.setOpaque(true);

        p1OriginalScore.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        p1OriginalScore.setText("p1Score");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("original Score:");

        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jPanel6.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel6.setLayout(new java.awt.GridLayout(1, 0));

        jPanel7.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel7.setLayout(new java.awt.GridLayout(1, 0));

        p1c1.setEditable(false);
        p1c1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        p1c1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        p1c1.setText("-");
        p1c1.setToolTipText("");
        p1c1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p1c1ActionPerformed(evt);
            }
        });
        jPanel7.add(p1c1);

        p1f1.setEditable(false);
        p1f1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        p1f1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        p1f1.setText("            ");
        p1f1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p1f1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(185, 185, 185)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(335, 335, 335)
                                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(p1f1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(p1f1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 96, Short.MAX_VALUE)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jPanel8.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel8.setLayout(new java.awt.GridLayout(1, 0));

        jPanel9.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel9.setLayout(new java.awt.GridLayout(1, 0));

        p1c21.setEditable(false);
        p1c21.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        p1c21.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        p1c21.setText("            ");
        jPanel9.add(p1c21);

        p1c22.setEditable(false);
        p1c22.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        p1c22.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        p1c22.setText("            ");
        p1c22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p1c22ActionPerformed(evt);
            }
        });
        jPanel9.add(p1c22);

        p1c23.setEditable(false);
        p1c23.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        p1c23.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        p1c23.setText("            ");
        p1c23.setAlignmentX(0.0F);
        p1c23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p1c23ActionPerformed(evt);
            }
        });
        jPanel9.add(p1c23);

        p1f2.setEditable(false);
        p1f2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        p1f2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        p1f2.setText("            ");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel5Layout.createSequentialGroup()
                            .addGap(256, 256, 256)
                            .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel5Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(0, 338, Short.MAX_VALUE)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(p1f2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(p1f2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout p1PanelLayout = new javax.swing.GroupLayout(p1Panel);
        p1Panel.setLayout(p1PanelLayout);
        p1PanelLayout.setHorizontalGroup(
            p1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p1PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(p1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(p1OriginalScore)
                    .addComponent(jLabel5))
                .addGap(52, 52, 52)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(66, Short.MAX_VALUE))
        );
        p1PanelLayout.setVerticalGroup(
            p1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p1PanelLayout.createSequentialGroup()
                .addGroup(p1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(p1PanelLayout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(p1OriginalScore))
                    .addGroup(p1PanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(p1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        p1Panel.setLayer(p1OriginalScore, javax.swing.JLayeredPane.DEFAULT_LAYER);
        p1Panel.setLayer(jLabel5, javax.swing.JLayeredPane.DEFAULT_LAYER);
        p1Panel.setLayer(jPanel4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        p1Panel.setLayer(jPanel5, javax.swing.JLayeredPane.DEFAULT_LAYER);

        p2Panel.setBorder(javax.swing.BorderFactory.createTitledBorder("Player1 Name"));
        p2Panel.setOpaque(true);

        p2OriginalScore.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        p2OriginalScore.setText("p1Score");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("original Score:");

        jPanel10.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jPanel11.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel11.setLayout(new java.awt.GridLayout(1, 0));

        jPanel12.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel12.setLayout(new java.awt.GridLayout(1, 0));

        p2c1.setEditable(false);
        p2c1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        p2c1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        p2c1.setText("            ");
        p2c1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p2c1ActionPerformed(evt);
            }
        });
        jPanel12.add(p2c1);

        p2f1.setEditable(false);
        p2f1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        p2f1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        p2f1.setText("            ");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(458, 458, 458)
                        .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(p2f1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(p2f1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel13.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jPanel14.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel14.setLayout(new java.awt.GridLayout(1, 0));

        jPanel15.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel15.setLayout(new java.awt.GridLayout(1, 0));

        p2c21.setEditable(false);
        p2c21.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        p2c21.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        p2c21.setText("            ");
        jPanel15.add(p2c21);

        p2c22.setEditable(false);
        p2c22.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        p2c22.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        p2c22.setText("            ");
        p2c22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p2c22ActionPerformed(evt);
            }
        });
        jPanel15.add(p2c22);

        p2c23.setEditable(false);
        p2c23.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        p2c23.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        p2c23.setText("            ");
        p2c23.setAlignmentX(0.0F);
        p2c23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p2c23ActionPerformed(evt);
            }
        });
        jPanel15.add(p2c23);

        p2f2.setEditable(false);
        p2f2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        p2f2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        p2f2.setText("            ");

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel13Layout.createSequentialGroup()
                            .addGap(256, 256, 256)
                            .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel13Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jPanel15, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(0, 338, Short.MAX_VALUE)))
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(p2f2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel15, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(p2f2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout p2PanelLayout = new javax.swing.GroupLayout(p2Panel);
        p2Panel.setLayout(p2PanelLayout);
        p2PanelLayout.setHorizontalGroup(
            p2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p2PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(p2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(p2OriginalScore)
                    .addComponent(jLabel6))
                .addGap(52, 52, 52)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(66, Short.MAX_VALUE))
        );
        p2PanelLayout.setVerticalGroup(
            p2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p2PanelLayout.createSequentialGroup()
                .addGroup(p2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(p2PanelLayout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(p2OriginalScore))
                    .addGroup(p2PanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(p2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(113, Short.MAX_VALUE))
        );
        p2Panel.setLayer(p2OriginalScore, javax.swing.JLayeredPane.DEFAULT_LAYER);
        p2Panel.setLayer(jLabel6, javax.swing.JLayeredPane.DEFAULT_LAYER);
        p2Panel.setLayer(jPanel10, javax.swing.JLayeredPane.DEFAULT_LAYER);
        p2Panel.setLayer(jPanel13, javax.swing.JLayeredPane.DEFAULT_LAYER);

        angleSlider.setMajorTickSpacing(30);
        angleSlider.setMaximum(180);
        angleSlider.setMinorTickSpacing(10);
        angleSlider.setPaintLabels(true);
        angleSlider.setPaintTicks(true);
        angleSlider.setSnapToTicks(true);
        angleSlider.setToolTipText("");
        angleSlider.setValue(90);
        angleSlider.setAutoscrolls(true);

        velocitySlider.setMajorTickSpacing(5);
        velocitySlider.setMinorTickSpacing(5);
        velocitySlider.setPaintLabels(true);
        velocitySlider.setPaintTicks(true);
        velocitySlider.setValue(10);

        jLabel2.setText("Angle");

        jLabel3.setText("Velocity");

        angleValue.setText("Value = ");

        velocityValue.setText("Value =");

        throwBallButton.setText("Throw Ball");
        throwBallButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                throwBallButtonActionPerformed(evt);
            }
        });

        exit.setLabel("Exit");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });

        display.setEditable(false);
        display.setColumns(20);
        display.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        display.setLineWrap(true);
        display.setRows(5);
        display.setWrapStyleWord(true);
        display.setAutoscrolls(false);
        display.setPreferredSize(new java.awt.Dimension(200, 100));
        jScrollPane1.setViewportView(display);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(71, 71, 71))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(59, 59, 59)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(velocitySlider, javax.swing.GroupLayout.DEFAULT_SIZE, 528, Short.MAX_VALUE)
                                    .addComponent(angleSlider, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(angleValue)
                                    .addComponent(velocityValue))
                                .addGap(72, 72, 72)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(p2Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(p1Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(throwBallButton)
                        .addGap(48, 48, 48)
                        .addComponent(exit)))
                .addContainerGap(867, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {p1Panel, p2Panel});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(125, 125, 125)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(p1Panel)
                            .addComponent(jScrollPane1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(p2Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(35, 35, 35)
                                        .addComponent(jLabel2))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(27, 27, 27)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(angleValue)
                                            .addComponent(angleSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(velocitySlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(velocityValue)))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(104, 104, 104)))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(throwBallButton)
                    .addComponent(exit))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {p1Panel, p2Panel});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void p1c22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p1c22ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_p1c22ActionPerformed

    private void p1c23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p1c23ActionPerformed
        // TODO add your hasdndling code here:
    }//GEN-LAST:event_p1c23ActionPerformed

    private void p2c1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p2c1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_p2c1ActionPerformed

    private void p2c22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p2c22ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_p2c22ActionPerformed

    private void p2c23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p2c23ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_p2c23ActionPerformed

    private void p1c1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p1c1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_p1c1ActionPerformed

    private void throwBallButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_throwBallButtonActionPerformed
                  
        chance++;
        if (chance == 1) {
            newScore= getRandom(10);
            if (newScore != 10) {
                p2c1.setText(String.valueOf(newScore));
            } else {
                p2c1.setText("X");
            }
            player2Score+=newScore;
            p2f1.setText(String.valueOf(player2Score));
            if(player2Score<player1Score)
            {
                display.setText(player1Name +" has won the game!!!!!!!!!");   
                throwBallButton.setEnabled(false);
            }
            else
            {
                display.setText(player2Name +" has become highest\n\n\n Both will get 3 additional frames to score");  
            }
        }
        if (chance == 2)
        {
            newScore = getRandom(10);
            if (newScore != 10) {
                p1c21.setText(String.valueOf(newScore));
            } else {
                p1c1.setText("X");
            }
            player1Score+=newScore;
            p1f2.setText(String.valueOf(player1Score));        
        }
        if (chance == 3)
        {
            int oldScore=newScore;
            newScore = getRandom(10-oldScore);
            if (newScore+oldScore != 10) {
                p1c22.setText(String.valueOf(newScore));
            } else {
                p1c22.setText("/");
            }
            player1Score+=newScore;
            p1f2.setText(String.valueOf(player1Score));   
            newScore=newScore+oldScore;
        }
        if (chance == 4)
        {
            int oldScore=newScore;
            newScore = getRandom(10-oldScore);
            if (newScore+oldScore != 10) {
                p1c23.setText(String.valueOf(newScore));
            } else {
                p1c23.setText("/");
            }
            player1Score+=newScore;
            p1f2.setText(String.valueOf(player1Score));        
        }
        if (chance == 5)
        {
            newScore = getRandom(10);
            if (newScore != 10) {
                p2c21.setText(String.valueOf(newScore));
            } else {
                p2c21.setText("X");
            }
            player2Score+=newScore;
            p2f2.setText(String.valueOf(player2Score));        
        }
        if (chance == 6)
        {
            int oldScore=newScore;
            newScore = getRandom(10-oldScore);
            if (newScore+oldScore != 10) {
                p2c22.setText(String.valueOf(newScore));
            } else {
                p2c22.setText("/");
            }
            player2Score+=newScore;
            p2f2.setText(String.valueOf(player2Score));   
            newScore=newScore+oldScore;
        }
        if (chance == 7)
        {
            int oldScore=newScore;
            newScore = getRandom(10-oldScore);
            if (newScore+oldScore != 10) {
                p2c23.setText(String.valueOf(newScore));
            } else {
                p2c23.setText("/");
            }
            player2Score+=newScore;
            p2f2.setText(String.valueOf(player2Score));   
            if(player2Score<player1Score)
            {
                display.setText(player1Name +" has won the game!!!!!!!!!");   
            }
            else
            {
                display.setText(player2Name +" has won the game!!!!!!!!!");               
            }
            
            throwBallButton.setEnabled(false);
        }
    }//GEN-LAST:event_throwBallButtonActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        setVisible(false);
    }//GEN-LAST:event_exitActionPerformed

    private void p1f1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p1f1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_p1f1ActionPerformed

    public int getRandom(int max) {

        int min = 0;
//        int max = 10;
        //Generate random int value from 50 to 100 
        System.out.println("Random value in int from " + min + " to " + max + ":");
        int random_int = (int) Math.floor(Math.random() * (max - min + 1) + min);
        return random_int;
    }
 
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(TieBreaker.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(TieBreaker.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(TieBreaker.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(TieBreaker.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
////        java.awt.EventQueue.invokeLater(new Runnable() {
////            public void run() {
////                
////                new TieBreaker().setVisible(true);
////            }
////        });
//        
//        TieBreaker tb = new TieBreaker("Kunal", "XYZ", 200, 200);
//        tb.setVisible(true);
//
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSlider angleSlider;
    private javax.swing.JLabel angleValue;
    private javax.swing.JTextArea display;
    private javax.swing.JButton exit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JLabel p1OriginalScore;
    private javax.swing.JLayeredPane p1Panel;
    private javax.swing.JTextField p1c1;
    private javax.swing.JTextField p1c21;
    private javax.swing.JTextField p1c22;
    private javax.swing.JTextField p1c23;
    private javax.swing.JTextField p1f1;
    private javax.swing.JTextField p1f2;
    private javax.swing.JLabel p2OriginalScore;
    private javax.swing.JLayeredPane p2Panel;
    private javax.swing.JTextField p2c1;
    private javax.swing.JTextField p2c21;
    private javax.swing.JTextField p2c22;
    private javax.swing.JTextField p2c23;
    private javax.swing.JTextField p2f1;
    private javax.swing.JTextField p2f2;
    private javax.swing.JButton throwBallButton;
    private javax.swing.JSlider velocitySlider;
    private javax.swing.JLabel velocityValue;
    // End of variables declaration//GEN-END:variables

    @Override
    public void stateChanged(ChangeEvent e) {
        angleValue.setText("Value = " + angleSlider.getValue());
        velocityValue.setText("Value = " + velocitySlider.getValue());
    }

//    public Boolean runTieBreaker() {
//        
//    }

    public void runTieBreaker(String player1Name, String player2Name, int player1Score, int player2Score) {
        initComponents();
        this.player1Name = player1Name;
        this.player2Name = player2Name;
        this.player1Score = player1Score;
        this.player2Score = player2Score;
        p1Panel.setBorder(BorderFactory.createTitledBorder(player1Name));
        p2Panel.setBorder(BorderFactory.createTitledBorder(player2Name));
        p2OriginalScore.setText(String.valueOf(player2Score));
        p1OriginalScore.setText(String.valueOf(player1Score));
        p1f1.setText(String.valueOf(player1Score));
        display.setText(player2Name +" is the 2nd highest player\n therefore he will get a chance to bowl"); 
        setVisible(true);
    }
}
